dist: xenial
language: ruby
rvm: 2.6.3
before_install:
  - export DRILL_VERSION=1.16.0
  - ./test/ci/install_drill.sh
cache:
  directories:
    - $HOME/drill
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
