name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.2
            drill: 1.21.1
          # TODO use archive
          # - ruby: 2.7
          #   drill: 1.18.0
    runs-on: ubuntu-latest
    env:
      DRILL_VERSION: ${{ matrix.drill }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: actions/cache@v3
        with:
          path: ~/drill
          key: drill-${{ env.DRILL_VERSION }}
        id: cache-drill
      - name: Download Drill
        if: steps.cache-drill.outputs.cache-hit != 'true'
        run: |
          wget -q https://dlcdn.apache.org/drill/$DRILL_VERSION/apache-drill-$DRILL_VERSION.tar.gz
          tar xfz apache-drill-$DRILL_VERSION.tar.gz
          mv apache-drill-$DRILL_VERSION ~/drill
      - name: Start Drill
        run: |
          screen -d -m ~/drill/bin/drill-embedded
          for i in {1..12}; do wget -O- -v http://127.0.0.1:8047/status && break || sleep 5; done
      - run: bundle exec rake test
